export type ViewLeadDataProps = {
  address: string;
  alternativeNumber: string;
  approximate_amount: string;
  area: string;
  assignedUserName: string;
  assigned_to: number;
  categoryName: string;
  cityName: string;
  company_name: string;
  competitor_id: number;
  competitor_name: string;
  countryName: string;
  country_code: number;
  customerCategoryId: number;
  customer_name: string;
  dealerActiveStatus: number;
  dealerId: number;
  dealerName: string;
  description: string;
  email: string;
  employeeActiveStatus: number;
  enquiryTypeId: number;
  enquiryTypeName: string;
  files: any[];
  leadCode: string;
  leadId: number;
  leadStatusId: number;
  leadStatusName: string;
  name: string;
  notes: string;
  phoneNumber: string;
  pincode: string;
  receivedAt: string;
  referNumber: string;
  referedBy: string;
  remarks: string;
  requirementsId: RequirementsDataProps[];
  schedule_date: string;
  stateName: string;
  transferComment: string;
  userName: string;
  whatsapp_no: string;
};

export type RequirementsDataProps = { reqId: number; reqName: string };
